CLASS ycl_s4d401_0070_26jv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_s4d401_0070_26jv IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.

  ENDMETHOD.

ENDCLASS.
